/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sylvernaut (https://sketchfab.com/sylvernaut)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-pawn-2b61573abd0a4599999e1ca0dffc4785
Title: Chess Pawn
*/

'use client'

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

export const Pawn = (props) => {
  const { nodes, materials } = useGLTF('/models/pawn-transformed.glb')

  const modelRef = useRef()

  useFrame((state, delta, xrFrame) => {
    modelRef.current.position.y = Math.sin(state.clock.elapsedTime) * 0.15
    modelRef.current.rotation.y += 0.01
  })

  materials['Scene_-_Root'].color.set(0xffffff)

  return (
    <group ref={modelRef} {...props} dispose={null} position={[0, 0, 0]} rotation={[0.25, 0, 0]} scale={[1.5, 1.5, 1.5]}>
      <mesh
        name="Object_2"
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.212}
      />
    </group>
  )
}

useGLTF.preload('/models/pawn-transformed.glb')
